version: '3'
services:
  starterkit:
    build:
      context: .
      dockerfile: Dockerfile.dev
    stdin_open: true
    tty: true
    ports:
      - '3000:8000'
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - ./.env
    command: npm run dev
