version: '3'
services:
  starterkit:
    build:
      context: .
      dockerfile: Dockerfile.dev
    stdin_open: true
    tty: true
    ports:
      - '8000:8000'
    volumes:
      - .:/app # Map the current directory to /app
    env_file:
      - ./.env
    command: npm run dev
